wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.11.2
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.7.9
    t:
      1:
      - 1
      - 5
      4: 3.7.9
      5: 0.11.2
      8:
      - 1
      - 5
